import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('../js/legacy-deletion.js',import.meta.url),'utf8');
const box={module:{exports:{}},AbortController};vm.runInNewContext(source,box);const {create}=box.module.exports;
const preview=id=>({legacy_id:id,subject_name:'Synthetic QA',confirmation_text:`DELETE LEGACY ${id}`,status:'available',counts:{}});
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve};};
function setup(overrides={}){let legacy={id:12,subject_name:'Synthetic QA',access_role:'owner'};const calls=[],deleted=[];const panel=create({getLegacy:()=>legacy,request:async(path,options)=>{calls.push({path,options});return options.method==='DELETE'?{legacy_id:12,status:'deleting'}:preview(12);},onDeleted:id=>deleted.push(id),...overrides});return {panel,calls,deleted,setLegacy:value=>legacy=value};}
test('opening and cancelling the hard warning never sends DELETE',async()=>{const {panel,calls}=setup();await panel.open();assert.equal(panel.canDelete(),false);panel.close();assert.equal(calls.length,1);assert.equal(calls[0].options.method,undefined);});
for(const role of ['collaborator','viewer','none'])test(`${role} cannot open deletion or call its API`,async()=>{const s=setup();s.setLegacy({id:12,access_role:role});await s.panel.open();assert.equal(s.calls.length,0);assert.equal(await s.panel.remove(),false);});
test('exact typed confirmation and explicit acknowledgement are both required',async()=>{const {panel,calls,deleted}=setup();await panel.open();for(const [text,ack] of [['',true],['DELETE LEGACY 13',true],['delete legacy 12',true],['DELETE LEGACY 12',false]]){panel.update(text,ack);assert.equal(await panel.remove(),false);}panel.update('DELETE LEGACY 12',true);assert.equal(await panel.remove(),true);assert.equal(calls.length,2);assert.equal(calls[1].path,'/legacies/12');assert.deepEqual(deleted,[12]);assert.equal(calls[1].options.body.acknowledge_permanent,true);});
test('late preview from the old Legacy cannot arm deletion',async()=>{const pending=deferred(),s=setup({request:()=>pending.promise});const open=s.panel.open();s.setLegacy({id:13,access_role:'owner'});s.panel.close();pending.resolve(preview(12));await open;assert.equal(s.panel.state.preview,null);assert.equal(s.panel.canDelete(),false);});
test('wrong server scope is rejected rather than substituted',async()=>{const {panel}=setup({request:async()=>preview(99)});await panel.open();assert.equal(panel.state.preview,null);assert.equal(panel.canDelete(),false);assert.match(panel.state.error,/selected Legacy changed/);});
test('repeated submission dispatches only one DELETE and cancellation cannot undo a dispatched request',async()=>{const pending=deferred();let count=0;const {panel}=setup({request:async(path,options)=>{if(options.method==='DELETE'){count++;return pending.promise;}return preview(12);}});await panel.open();panel.update('DELETE LEGACY 12',true);const first=panel.remove();assert.equal(await panel.remove(),false);assert.equal(panel.close(),false);pending.resolve({legacy_id:12,status:'deleting'});assert.equal(await first,true);assert.equal(count,1);});
test('API failure never claims successful deletion',async()=>{const {panel,deleted}=setup({request:async(path,options)=>{if(options.method==='DELETE')throw Error('Network unavailable');return preview(12);}});await panel.open();panel.update('DELETE LEGACY 12',true);assert.equal(await panel.remove(),false);assert.equal(panel.state.open,true);assert.match(panel.state.error,/Network unavailable/);assert.deepEqual(deleted,[]);});
test('warning names full deletion scope and safe cancellation is the initial focus',()=>{for(const phrase of ['cannot be undone','memories, chats, timeline','uploaded photos and documents','prepared portraits','Visitors and collaborators will lose access','Your account and other Legacies will not be deleted','Keep Legacy','keep.focus()'])assert.ok(source.includes(phrase));const html=readFileSync(new URL('../chat.html',import.meta.url),'utf8');assert.match(html,/id="deleteLegacy"[^>]*hidden/);assert.ok(html.indexOf('id="deleteLegacy"')>html.indexOf('id="legacyMenu"'));assert.doesNotMatch(readFileSync(new URL('../legacy-chat.html',import.meta.url),'utf8'),/legacy-deletion|deleteLegacy/);});
