import test from "node:test";
import assert from "node:assert/strict";
import vm from "node:vm";
import { readFileSync } from "node:fs";
import { webcrypto, createHash } from "node:crypto";
import { SquareCrop } from "../js/visual-crop.mjs";
import { MouthEnvelope, outputEnvelope } from "../js/playback-envelope.mjs";
import { createVisualClient, validateManifest, validateRig } from "../js/visual-presence-client.mjs";
import { createVisualPresence } from "../js/visual-presence-controller.mjs";
import { RealtimePlayback } from "../js/realtime-playback.mjs";
import { RealtimeClient } from "../js/realtime-client.mjs";

const id=n=>`${String(n).padStart(8,"0")}-1111-4111-8111-111111111111`, hash=value=>createHash("sha256").update(value).digest("hex");
function rigFixture() { return {recipe_version:"portrait_2d_v1",topology_version:1,fake_only:false,request_identity_sha256:"a".repeat(64),atlas_sha256:"b".repeat(64),poster_sha256:"c".repeat(64),atlas_size:[512,512],crop_rect:[0,0,512,512],patches:{mouth:[.2,.6,.6,.3],blink_left:[.1,.2,.3,.2],blink_right:[.6,.2,.3,.2]},vertices:[[0,0],[1,0],[1,1],[0,1]],uvs:[[0,0],[1,0],[1,1],[0,1]],triangles:[[0,1,2],[0,2,3]],deformations:{mouth:[0,0,0,0],blink_left:[0,0,0,0],blink_right:[0,0,0,0]}}; }
function manifest(version=null) { return {version_id:version||id(1),revision:1,recipe:"portrait_2d_v1",bundle_digest:"e".repeat(64),lease_seconds:15,valid_until:new Date(15000).toISOString(),assets:["poster","rig","texture_atlas"].map((role,i)=>({id:id(i+2),role,mime_type:role==="rig"?"application/json":"image/png",byte_size:100,sha256:"d".repeat(64),content_path:`/api/v1/legacies/1/visual-companion/${version?`versions/${version}`:"active"}/assets/${id(i+2)}/content`}))}; }
for(const [width,height] of [[1200,800],[800,1200],[128,128],[8192,2048],[627,627]])test(`square crop remains physical 1:1 through pan/zoom/rotation ${width}x${height}`,()=>{
  const crop=new SquareCrop(width,height);
  for(let r=0;r<4;r++) {for(const z of [1,1.27,2,4,200]){crop.zoom(z).pan(100000,-100000);const c=crop.value();assert.ok(Math.abs(c.width*crop.width-c.height*crop.height)<=1e-6);assert.ok(c.x>=0&&c.y>=0&&c.x+c.width<=1&&c.y+c.height<=1);assert.ok(crop.edge>=128);}crop.rotate();}
  assert.equal(crop.rotation,0);crop.reset();assert.equal(crop.edge,Math.min(width,height));
});
for(const dimensions of [[0,200],[127,512],[8193,128],[6000,6000],[NaN,200]])test(`invalid image dimensions rejected: ${dimensions}`,()=>assert.throws(()=>new SquareCrop(...dimensions)));
test("quarter-turn preserves the manually selected region without choosing another person",()=>{const c=new SquareCrop(1000,800).zoom(2).pan(-100,100);const before={x:c.x,y:c.y,edge:c.edge};for(let i=0;i<4;i++)c.rotate();assert.deepEqual({x:c.x,y:c.y,edge:c.edge},before);});
test("20ms output windows preserve internal silence and clamp RMS",()=>{const samples=new Float32Array(24000);samples.fill(.1,0,480);samples.fill(1,960,1440);const points=outputEnvelope(samples);assert.equal(points.length,50);assert.ok(Math.abs(points[0].value-.6)<1e-6);assert.equal(points[1].value,0);assert.equal(points[2].value,1);assert.equal(points[2].offset,.04);});
test("mouth uses hysteresis, 30ms attack, 90ms release and hard silence reset",()=>{const m=new MouthEnvelope();assert.equal(m.step(.07,.03),0);assert.ok(Math.abs(m.step(1,.03)-(1-Math.exp(-1)))<1e-8);assert.ok(m.step(.06,.03)>0);for(let i=0;i<8;i++)m.step(0,.02);assert.equal(m.value,0);m.step(1,.03);m.reset();assert.equal(m.value,0);assert.equal(m.open,false);});
test("valid manifest is scoped to the exact Legacy, preview version and private routes",()=>{validateManifest(manifest(),1);validateManifest(manifest(id(9)),1,id(9));assert.throws(()=>validateManifest(manifest(),2));assert.throws(()=>validateManifest(manifest(id(9)),1,id(10)));});
const badManifests={"external URL":m=>m.assets[0].content_path="https://evil.invalid/photo","query token":m=>m.assets[0].content_path+="?token=x","wrong role":m=>m.assets[0].role="video","duplicate role":m=>m.assets[1].role="poster","large asset":m=>m.assets[0].byte_size=3000000,"unknown recipe":m=>m.recipe="video_v2","bad hash":m=>m.bundle_digest="x","long lease":m=>m.lease_seconds=16,"string lease":m=>m.lease_seconds="15","invalid expiry":m=>m.valid_until="tomorrow","wrong preview route":m=>m.assets[0].content_path=m.assets[0].content_path.replace("active","versions/"+id(9))};
for(const [name,mutate] of Object.entries(badManifests))test(`reject malformed manifest: ${name}`,()=>{const m=manifest();mutate(m);assert.throws(()=>validateManifest(m,1));});
test("numeric full-square rig passes",()=>validateRig(rigFixture()));
const badRigs={"executable payload":r=>r.script="fetch('evil')","fake production rig":r=>r.fake_only=true,"unknown field":r=>r.voice_id="forbidden","NaN":r=>r.vertices[0][0]=NaN,"infinite motion":r=>r.deformations.mouth[0]=Infinity,"edge motion":r=>r.deformations.mouth[0]=.001,"wrong UV":r=>r.uvs[1][0]=.2,"flipped triangle":r=>r.triangles[0]=[0,2,1],"duplicate triangle":r=>r.triangles[1]=r.triangles[0],"missing coverage":r=>r.triangles.pop(),"oversized topology":r=>r.vertices=Array(513).fill([0,0]),"non-square crop":r=>r.crop_rect[3]=256};
for(const [name,mutate] of Object.entries(badRigs))test(`reject malformed rig: ${name}`,()=>{const r=rigFixture();mutate(r);assert.throws(()=>validateRig(r));});

function clock() {let time=0,serial=0;const timers=new Map();return {timers,performance:{now:()=>time},Date:{now:()=>time},setTimeout(fn,delay){const id=++serial;timers.set(id,{fn,due:time+delay});return id;},clearTimeout(id){timers.delete(id);},advance(ms){time+=ms;for(const [id,t]of [...timers])if(t.due<=time){timers.delete(id);t.fn();}},get time(){return time;}};}
const flush=()=>new Promise(resolve=>setImmediate(resolve));
function controllerHarness(overrides={}) {
  const environment=clock(),made=[],bundles=[];let allowed=true,fetches=0;
  const host={dataset:{},ownerDocument:{createElement:()=>({})},replaceChildren(...nodes){this.nodes=nodes;}};
  const client={async manifest(){fetches++;return {...manifest(),valid_until:new Date(environment.time+15000).toISOString()};},async bundle(m){const b={manifest:m,disposed:0,dispose(){this.disposed++;}};bundles.push(b);return b;},...overrides};
  const rendererFactory=(_host,_bundle,options)=>{const r={options,disposed:0,resets:0,reset(){this.resets++;},setStatic(){},diagnostics(){return{};},dispose(){this.disposed++;}};made.push(r);return r;};
  const controller=createVisualPresence({host,client,legacyId:1,environment,rendererFactory,guard:()=>allowed});
  return {controller,environment,client,host,made,bundles,setAllowed(value){allowed=value;},get fetches(){return fetches;}};
}
const binding={session_id:"s",generation:1,turn_id:1,active_generation_id:"g",response_id:"r",playback_epoch:1};
const envelope=(extra={})=>({type:"playback_envelope",...binding,value:1,audio_time:1,due:1,expires:1.02,...extra});
test("fenced assistant envelope alone moves the mouth; reset is synchronous",async()=>{const h=controllerHarness();await h.controller.start();h.controller.presentation({type:"playback_binding",...binding});h.controller.presentation(envelope());assert.ok(h.made[0].options.sample(.03,0).mouth>0);h.controller.presentation({type:"playback_reset",playback_epoch:2});assert.equal(h.controller.diagnostics().mouth,0);assert.ok(h.made[0].resets>0);h.controller.presentation(envelope());assert.equal(h.made[0].options.sample(.03,0).mouth,0);h.controller.dispose();});
for(const field of ["session_id","generation","turn_id","active_generation_id","response_id","playback_epoch"])test(`output identity fences stale ${field}`,async()=>{const h=controllerHarness();await h.controller.start();h.controller.presentation({type:"playback_binding",...binding});h.controller.presentation(envelope({[field]:"other"}));assert.equal(h.made[0].options.sample(.03,0).mouth,0);h.controller.dispose();});
for(const type of ["input_energy","output_energy","transcript_final","assistant_audio","thinking"])test(`non-playback event cannot drive portrait: ${type}`,async()=>{const h=controllerHarness();await h.controller.start();h.controller.presentation({type:"playback_binding",...binding});h.controller.presentation(envelope({type}));assert.equal(h.made[0].options.sample(.03,0).mouth,0);h.controller.dispose();});
test("internal silent output closes without waiting for provider done",async()=>{const h=controllerHarness();await h.controller.start();h.controller.presentation({type:"playback_binding",...binding});h.controller.presentation(envelope());h.made[0].options.sample(.03,0);for(let i=1;i<=9;i++)h.made[0].options.sample(.02,i*20);assert.equal(h.controller.diagnostics().mouth,0);h.controller.dispose();});
test("failed lease refresh removes bitmap/poster immediately, never stale fallback",async()=>{const h=controllerHarness();await h.controller.start();h.client.manifest=async()=>{throw new Error("offline");};h.environment.advance(5000);await flush();assert.equal(h.bundles[0].disposed,1);assert.equal(h.made[0].disposed,1);assert.equal(h.controller.approval(),null);assert.equal(h.environment.timers.size,0);assert.equal(h.host.dataset.visualState,"ERROR");});
test("hung refresh cannot extend the original fifteen-second lease",async()=>{const h=controllerHarness();await h.controller.start();h.client.manifest=()=>new Promise(()=>{});h.environment.advance(5000);await flush();h.environment.advance(10000);assert.equal(h.bundles[0].disposed,1);assert.equal(h.controller.approval(),null);assert.equal(h.environment.timers.size,0);});
test("late asset completion after close disposes bytes without installing renderer",async()=>{let resolve;const h=controllerHarness({bundle:()=>new Promise(r=>resolve=r)});const pending=h.controller.start();await flush();h.controller.dispose();const b={disposed:0,dispose(){this.disposed++;}};resolve(b);await pending;assert.equal(b.disposed,1);assert.equal(h.made.length,0);assert.equal(h.environment.timers.size,0);});
test("Legacy switch while loading never installs old portrait",async()=>{let resolve;const h=controllerHarness({manifest:()=>new Promise(r=>resolve=r)});const pending=h.controller.start();h.setAllowed(false);resolve(manifest());await pending;assert.equal(h.made.length,0);h.controller.dispose();assert.equal(h.environment.timers.size,0);});
test("replacement revokes v1 before delayed v2 asset load",async()=>{const h=controllerHarness();await h.controller.start();let resolve;h.client.manifest=async()=>({...manifest(),version_id:id(9),revision:2,valid_until:new Date(20000).toISOString()});h.client.bundle=()=>new Promise(r=>resolve=r);h.environment.advance(5000);await flush();assert.equal(h.bundles[0].disposed,1);assert.equal(h.controller.approval(),null);h.controller.dispose();const b={disposed:0,dispose(){this.disposed++;}};resolve(b);await flush();assert.equal(b.disposed,1);assert.equal(h.made.length,1);});
test("50 calls and 100 load cycles retain zero resources after disposal",async()=>{const h=controllerHarness();for(let i=0;i<100;i++)await h.controller.start();h.controller.dispose();assert.equal(h.bundles.length,100);assert.ok(h.bundles.every(b=>b.disposed===1));assert.ok(h.made.every(r=>r.disposed===1));assert.equal(h.environment.timers.size,0);for(let i=0;i<50;i++){const call=controllerHarness();await call.controller.start();call.controller.dispose();assert.equal(call.environment.timers.size,0);}});

function playbackHarness(observer=()=>{}) {
  const env=clock(),events=[],sources=[],seen=[];const context={state:"running",get currentTime(){return env.time/1000;},outputLatency:.1,baseLatency:0,destination:{},createBuffer(_,count,rate){return{duration:count/rate,getChannelData:()=>new Float32Array(count)};},createBufferSource(){const s={connect(){},disconnect(){},start(t){this.startTime=t;},stop(){seen.push("stop");}};sources.push(s);return s;}};
  const playback=new RealtimePlayback({context,environment:{...env,setTimeout:env.setTimeout,clearTimeout:env.clearTimeout,atob:s=>Buffer.from(s,"base64").toString("binary")},send:e=>events.push(e),onPresentation:e=>{seen.push(e.type);observer(e);}});
  playback.begin(binding);return {playback,env,events,sources,seen};
}
test("output observer waits for scheduled audio plus device latency, not packet arrival",()=>{const observed=[],h=playbackHarness(e=>observed.push(e));const pcm=Buffer.alloc(4800);for(let i=0;i<480;i++)pcm.writeInt16LE(16000,i*2);h.playback.frame({...binding,sequence:0,pcm:pcm.toString("base64")});h.env.advance(120);assert.equal(observed.filter(e=>e.type==="playback_envelope").length,0);h.env.advance(6);assert.ok(observed.at(-1).value>.9);h.env.advance(20);assert.equal(observed.at(-1).value,0);h.playback.clear();assert.equal(h.env.timers.size,0);});
test("visual neutral reset precedes every source stop and transport cancellation",()=>{const h=playbackHarness();h.playback.frame({...binding,sequence:0,pcm:Buffer.alloc(2400).toString("base64")});const client=Object.create(RealtimeClient.prototype);client.playback=h.playback;client.sendPlayback=()=>h.seen.push("cancel");client.stopSpeaking();assert.ok(h.seen.indexOf("playback_reset")<h.seen.indexOf("stop"));assert.ok(h.seen.indexOf("stop")<h.seen.indexOf("cancel"));});
test("throwing visual observer cannot change audio scheduling or stop behavior",()=>{const h=playbackHarness(()=>{throw new Error("visual only");});assert.doesNotThrow(()=>h.playback.frame({...binding,sequence:0,pcm:Buffer.alloc(2400).toString("base64")}));assert.equal(h.sources.length,1);assert.doesNotThrow(()=>h.playback.clear());assert.equal(h.env.timers.size,0);});
test("late known response ID updates the existing presentation binding",()=>{const seen=[],h=playbackHarness(e=>seen.push(e));h.playback.clear();h.playback.begin({...binding,active_generation_id:"g2",response_id:null});h.playback.begin({...binding,active_generation_id:"g2",response_id:"r2"});assert.equal(seen.at(-1).response_id,"r2");assert.equal(seen.at(-1).type,"playback_binding");h.playback.clear();});

test("private raw visual client pins route, method, origin, no-store and no redirects",async()=>{
  const calls=[],window={LEGARYA_AUTH_CONFIG:{apiBaseUrl:"/api/v1",mediaBaseUrl:"https://89-167-14-211.sslip.io/api/v1"}};
  vm.runInNewContext(readFileSync(new URL("../js/auth-api.js",import.meta.url),"utf8"),{window,Headers,localStorage:{setItem(){},removeItem(){}},fetch:async(url,options)=>{calls.push({url,options});return{ok:true,status:200};}});
  const auth=window.LegaryaAuthApi;auth.storeAuthenticatedSession({access_token:"synthetic-test-token",token_type:"bearer",user:{id:1}});
  const path=manifest().assets[0].content_path.slice(7);await auth.authenticatedVisualFetch(path);
  assert.equal(calls[0].options.cache,"no-store");assert.equal(calls[0].options.redirect,"error");assert.equal(calls[0].options.method,"GET");
  for(const bad of [path+"?token=x",path+"/..","https://evil.invalid",path.replace("active",".."),"/legacies/1/sources/x/content"])assert.throws(()=>auth.authenticatedVisualFetch(bad));
  assert.throws(()=>auth.authenticatedVisualFetch(path,{method:"PUT"}));assert.equal(calls.length,1);
});
async function bundleHarness() {
  const bytes={poster:new Uint8Array([1,2]),texture_atlas:new Uint8Array([3,4])},rig=rigFixture();rig.atlas_sha256=hash(bytes.texture_atlas);rig.poster_sha256=hash(bytes.poster);bytes.rig=new TextEncoder().encode(JSON.stringify(rig));
  const m=manifest();for(const a of m.assets){a.sha256=hash(bytes[a.role]);a.byte_size=bytes[a.role].length;}
  m.bundle_digest=hash(JSON.stringify({assets:[...m.assets].sort((a,b)=>a.role.localeCompare(b.role)).map(a=>({byte_size:a.byte_size,mime_type:a.mime_type,role:a.role,sha256:a.sha256})),recipe:m.recipe}));
  const created=[],revoked=[],bitmaps=[],responses=[];
  const auth={authenticatedVisualFetch:async path=>{const a=m.assets.find(a=>a.content_path.slice(7)===path);const response=new Response(bytes[a.role],{headers:{"Content-Type":a.mime_type}});responses.push(response);return response;}};
  const environment={crypto:webcrypto,URL:{createObjectURL(){created.push("blob:synthetic");return"blob:synthetic";},revokeObjectURL:u=>revoked.push(u)},async createImageBitmap(blob){const b={width:blob.size===2&&new Uint8Array(await blob.arrayBuffer())[0]===1?256:512,height:0,closed:0,close(){this.closed++;}};b.height=b.width;bitmaps.push(b);return b;}};
  return {client:createVisualClient(auth,environment),m,bytes,environment,created,revoked,bitmaps,responses};
}
test("verified private bundle closes both image bitmaps and revokes its Blob URL exactly once",async()=>{const h=await bundleHarness();const b=await h.client.bundle(h.m);assert.equal(h.created.length,1);b.dispose();b.dispose();assert.equal(h.revoked.length,1);assert.ok(h.bitmaps.every(b=>b.closed===1));});
test("bundle descriptor digest mismatch is rejected before reading any asset",async()=>{const h=await bundleHarness();h.m.bundle_digest="f".repeat(64);await assert.rejects(h.client.bundle(h.m));assert.equal(h.responses.length,0);});
test("oversized body is rejected before image decode or URL allocation",async()=>{const h=await bundleHarness();h.bytes.poster=new Uint8Array([1,2,3]);await assert.rejects(h.client.bundle(h.m));assert.equal(h.bitmaps.length,0);assert.equal(h.created.length,0);});
test("corrupted byte checksum is rejected before image decode",async()=>{const h=await bundleHarness();h.bytes.poster[0]=9;await assert.rejects(h.client.bundle(h.m));assert.equal(h.bitmaps.length,0);});
test("abort after image decode closes resources and cannot create a URL",async()=>{const h=await bundleHarness(),abort=new AbortController(),original=h.environment.createImageBitmap;h.environment.createImageBitmap=async blob=>{const b=await original(blob);abort.abort();return b;};await assert.rejects(h.client.bundle(h.m,abort.signal));assert.ok(h.bitmaps.every(b=>b.closed===1));assert.equal(h.created.length,0);});
test("account epoch changes on identity switch and before pending logout, not same-user refresh",async()=>{
  const events=[],window={LEGARYA_AUTH_CONFIG:{apiBaseUrl:"/api/v1"},dispatchEvent:event=>events.push(event.type)};let complete;
  vm.runInNewContext(readFileSync(new URL("../js/auth-api.js",import.meta.url),"utf8"),{window,Event,Headers,localStorage:{setItem(){},removeItem(){}},fetch:()=>new Promise(r=>complete=r)});
  const auth=window.LegaryaAuthApi,session=user=>({access_token:"synthetic",token_type:"bearer",user:{id:user}});
  auth.storeAuthenticatedSession(session(1));const first=auth.getSessionEpoch();auth.storeAuthenticatedSession(session(1));assert.equal(auth.getSessionEpoch(),first);
  auth.storeAuthenticatedSession(session(2));assert.equal(auth.getSessionEpoch(),first+1);const logout=auth.logout();assert.equal(auth.getSessionEpoch(),first+2);assert.equal(events.at(-1),"legarya:session-ending");complete({ok:true,status:204});await logout;assert.equal(auth.getSessionEpoch(),first+3);
});
test("silence hard deadline neutralizes without waiting for another animation frame",async()=>{const h=controllerHarness();await h.controller.start();h.controller.presentation({type:"playback_binding",...binding});h.controller.presentation(envelope());assert.ok(h.made[0].options.sample(.03,0).mouth>0);h.environment.advance(170);assert.equal(h.controller.diagnostics().mouth,0);h.controller.dispose();});
test("20ms speech windows remain visible between 15fps drawing ticks",async()=>{const h=controllerHarness();await h.controller.start();h.controller.presentation({type:"playback_binding",...binding});h.controller.presentation(envelope());h.environment.advance(50);assert.ok(h.made[0].options.sample(.05,50).mouth>.1);h.environment.advance(120);assert.equal(h.controller.diagnostics().mouth,0);h.controller.dispose();});
test("static preference toggle preserves the current authorized output binding",async()=>{const h=controllerHarness();await h.controller.start();h.controller.presentation({type:"playback_binding",...binding});h.controller.setStatic(true);h.controller.setStatic(false);h.controller.presentation(envelope());assert.ok(h.made[0].options.sample(.03,0).mouth>0);h.controller.dispose();});
test("listening and thinking states stay neutral independently of microphone energy",async()=>{const h=controllerHarness();await h.controller.start();h.controller.setCallState("capturing");assert.equal(h.controller.diagnostics().state,"LISTENING");h.controller.setCallState("thinking");assert.equal(h.controller.diagnostics().state,"THINKING");assert.equal(h.made[0].options.sample(.03,0).mouth,0);h.controller.dispose();});
test("static portrait expires even when external scope guard changed without a frame",async()=>{const h=controllerHarness();await h.controller.start();h.controller.setStatic(true);h.setAllowed(false);h.environment.advance(15000);assert.equal(h.bundles[0].disposed,1);assert.equal(h.controller.approval(),null);assert.equal(h.environment.timers.size,0);});
